server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/livepix
    username: SEU USER
    password: SUA SENHA
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

mercadopago:
  base-url: https://api.mercadopago.com
  access-token: SEU TOKEN DE ACESSO NO MERCADO PAGO
  webhook-secret: SEU WEBHOOK SECRET NO MERCADO PAGO
  webhook-verify-enabled: false
  default-payer-email: AQUI DEFINI UM EMAIL DEFAULT MAS O CORRETO SERIA PEDIR O EMAIL DE QUEM VAI FAZER A TRANSACAO NA API
